apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-manager
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.my_repository }}
        revision: {{ .Values.my_revision }}
        directories:
          - path: 'applicationsets'
		    helm:
		      valueFiles:
		        - values.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.my_repository }}
        targetRevision: {{ .Values.my_revision }}
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

